### ISSUE TITLE
NoClassDefFoundError running any Jython script

### ISSUE THREAD

**Issue by tracymiranda** [eclipse-ease-addons/jython#2]
In build 0.3.0 I can no longer run any jython script. 

To reproduce:
1. Using Eclipse Mars1, install EASE http://download.eclipse.org/ease/update/release (I installed Core, Lang/EASE Python and Modules/EASE Modules (Incubation)
2. Install Jython Engine from https://dl.bintray.com/pontesegger/ease-jython/
3. Create a new general project 'Test'
4. Add hello.py with contents 
print "hello world"
5. Select and do Run As-> EASE, see failure with this error

java.lang.NoClassDefFoundError: org/eclipse/ease/lang/python/PythonHelper
	at org.eclipse.ease.lang.python.jython.JythonScriptEngine.internalSetVariable(JythonScriptEngine.java:296)
	at org.eclipse.ease.AbstractScriptEngine.setVariable(AbstractScriptEngine.java:427)
	at org.eclipse.ease.AbstractScriptEngine.run(AbstractScriptEngine.java:215)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by tracymiranda** [comment]
Issue is caused by using the release (0.2.0) with Jython Engine 0.3.0
