### ISSUE TITLE
TypeError: 'javapackage' object is not callable

### ISSUE THREAD

**Issue by hotmaskim** [eclipse-ease-addons/jython#3]
Hello,

I want to create  python script that call some distante website.
For that, I try to use urllib but when I run my script, I have this error :

> Traceback (most recent call last):
  File "(none)", line 1, in <module>
  File "/Users/M/Desktop/eclipse/plugins/org.jython_2.7.0.201602120922/Lib/urllib.py", line 26, in <module>
    import socket
  File "/Users/M/Desktop/eclipse/plugins/org.jython_2.7.0.201602120922/Lib/socket.py", line 3, in <module>
    from _socket import (
  File "/Users/M/Desktop/eclipse/plugins/org.jython_2.7.0.201602120922/Lib/_socket.py", line 5, in <module>
    import logging
  File "/Users/M/Desktop/eclipse/plugins/org.jython_2.7.0.201602120922/Lib/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref
  File "/Users/M/Desktop/eclipse/plugins/org.jython_2.7.0.201602120922/Lib/weakref.py", line 71, in <module>
    WeakValueDictionaryBuilder = dict_builder(MapMaker().weakValues().makeMap, WeakValueDictionary)
TypeError: 'javapackage' object is not callable

I try different import (like subprocess), and the problem is the same and seems to come from this line :     
`WeakValueDictionaryBuilder = dict_builder(MapMaker().weakValues().makeMap, WeakValueDictionary)`

Do you know how I can have this feature work ?

**Comment by hotmaskim** [comment]
Oki, it works now.
thank you ;)
See this link : https://www.eclipse.org/forums/index.php/mn/msg/1075743/1/on/0/?SQ=523051ade662e1ac5dd4edaa511624a2
